spring:
  application:
    name: user-service
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/autoecole
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

server:
  port: 3001
