spring:
  cloud:
    function:
      definition: saveFormula
    stream:
      defaultBinder: kafka
      kafka:
        binder:
          brokers:
            - localhost:29092
      bindings:
        saveFormula-in-0:
          destination: send-communication
          group: test
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active:
      - "prod"
  application:
    name: user-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL_USER_SERVICE:jdbc:postgresql://localhost:5432/autoecole-user}
    username: ${SPRING_POSTGRES_USERNAME:postgres}
    password: ${SPRING_POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

server:
  port: 3001

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
  health:
    probes:
      enabled: true
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true



eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


info:
  app:
    name: "user-service"
    description: "user service microservice"