spring:
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active:
      - "prod"
  application:
    name: user-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL_USER_SERVICE:jdbc:postgresql://localhost:5432/autoecole}
    username: ${SPRING_POSTGRES_USERNAME:postgres}
    password: ${SPRING_POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

server:
  port: 3001
