CREATE TABLE public.adress (
    id BIGINT NOT NULL,
    adress_line1 VARCHAR(255),
    city VARCHAR(255),
    country VARCHAR(255),
    postal_code VARCHAR(255)
);

ALTER TABLE public.adress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.adress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_roles (
    user_id BIGINT NOT NULL,
    roles VARCHAR(255),
    CONSTRAINT user_roles_roles_check
        CHECK (((roles)::TEXT = ANY ((ARRAY[
            'ROLE_USER'::VARCHAR,
            'ROLE_ADMIN'::VARCHAR,
            'ROLE_TEACHER'::VARCHAR
        ])::TEXT[])))
);

CREATE TABLE public.users (
    id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    firstname VARCHAR(255),
    formula_id BIGINT,
    lastname VARCHAR(255),
    mail VARCHAR(255),
    password VARCHAR(255),
    phone VARCHAR(255),
    adress_id BIGINT
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.adress
    ADD CONSTRAINT adress_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukjhck7kjdogc7yia7qamc89ypv UNIQUE (mail);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkgdsep426iu4hj2mfu7ucpj0ds
        FOREIGN KEY (adress_id) REFERENCES public.adress(id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f
        FOREIGN KEY (user_id) REFERENCES public.users(id);
